spring:
  application:
    name:
      CooperationCenter
  thymeleaf:
    prefix:
      classpath:/templates/
    suffix:
      .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cooperationcenter?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: CooperationCenter
    password: cooperationcenter123!@#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mysql:
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
  servlet:
    multipart:
      enabled: true


jwt:
  secret: ZGZsbTJwM2ttZndlb2lmbjEzOTRnbnVxZWYxMjM1Zmdhc2RmZzQ0NHdkZjM0YXNkZjhhc2RmOTM0ZA==

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
