spring:
  application:
    name: CooperationCenter
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    show-sql: false           # 공통 기본값은 조용하게
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.format_sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true