spring:
  application:
    name: CooperationCenter
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    show-sql: false           # 공통 기본값은 조용하게
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.format_sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com


server:
  port: ${PORT:8080}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

mailgun:
  domain: ${MALIGUN_DOMAIN}
  api-key: ${MALIGUN_APIKEY}
  from-email: ${MALIGUN_FROMEMAIL}